### ISSUE TITLE
Бот перестал отпинивать сообщения. 

### ISSUE THREAD

**Issue by VikSing88** [VikSing88/SlackBot#12]
Бот в пишет только, что консультация закрыта, но не отпинивает ее и не ставит соответствующий эмодзи.

**Comment by aledyad** [comment]
Оказалось, что дефект появился из-за того, что удалили вызов Console.ReadKey() в методе Main.
Скорее всего проблема связана с асинхронными вызовами AddEmoji и UnpinMessage - они не успевают выполниться до завершения процесса.

С асинхронными вызовами будем разбираться в рамках #6 , а сейчас надо просто вернуть Console.ReadKey();
