### ISSUE TITLE
Сделать выборочное отключение автопина

### ISSUE THREAD

**Issue by morthan** [VikSing88/SlackBot#22]
Хотелось бы выборочно отключать автопин на время моего дежурства. От него больше вреда, чем пользы:

1. Теряется маркер того, что задачей уже кто-то занимается. Пользователь видит, что робот пинит консультацию сразу, и это не даёт ему никакой информации, увидел ли эту задачу живой человек.
2. Когда я запиниваю консультацию, то меня уведомляют о всех изменениях, даже если я пока ещё ничего туда не писал. Если задача запинена ботом, я не получаю никаких уведомлений и могу что-то пропустить.

**Comment by aledyad** [comment]
По п.1 - у нас нигде не прописано, как пользователь должен трактовать факт запиненности. И он не должен беспокоиться о том, взял ли его вопрос кто-то в работу. Он должен только знать, что все вопросы рассматриваются в порядке очереди, и рано или поздно ему ответят. Но если дежурный свободен, и не занимается новым вопросом, то это проблема дежурного, а не пользователя.
Дежурный должен вести все активные (запиненные) консультации, а не только те, которые он увидел.

По п.2 лучше оформить отдельно пожелание подписывать дежурного на запиненные консультации в начале дежурства.
