### ISSUE TITLE
Использовать SlackNet в качестве клиента.

### ISSUE THREAD

**Issue by KorepanovAV** [VikSing88/SlackBot#3]
Сейчас все общение написано вручную, но есть:
https://www.nuget.org/packages/SlackNet/
, который, может значительно облегчить жизнь.

**Comment by HolySpiridon** [comment]
SlackNet не подходит для роли клиента, так как у него нет подходящих методов чтения чата, но он позволяет отслеживать и реагировать на входящие сообщения бота с помощью создания обработчика event`a библиотеки (вот тут есть примеры в категории SlackNet.Bot https://github.com/soxtoby/SlackNet)

**Comment by KorepanovAV** [comment]
>SlackNet не подходит для роли клиента, так как у него нет подходящих методов чтения чата
Каких, например?

В обще, насколько я понимаю, сам SlackNet это обёртка над WebApi Slack и по идее все возможности должны (ели их добавил разработчик) быть. А уже SlackNet.Bot это надстройка над SlackNet для более удобного написания ботов.

* https://github.com/soxtoby/SlackNet/blob/master/SlackNet/SlackApiClient.cs - это обёртка над WebApi.
* https://github.com/soxtoby/SlackNet/blob/master/SlackNet/SlackRtmClient.cs - это использует ISlackApiClient для "Real Time Messaging API".

**Comment by HolySpiridon** [comment]
Да, в самом деле я не прав. Я не нашел, когда впервые смотрел методы Get и Post, позволяющие достучаться до методов slack`а, поэтому и подумал, что их нет
