### ISSUE TITLE
Добавить возможность скачивания всей беседы и вложений из треда.

### ISSUE THREAD

**Issue by VikSing88** [VikSing88/SlackBot#4]
По команде боту бот скачивает тред, все картинки, файлы, вложения, и запаковывает все в zip-архив.
тред: переписка в текстовом виде

**Comment by aledyad** [comment]
Шишков Александр(ОРПД5)  < 1 minute ago
Выгрузка всего треда есть в SlackHistoryExporter - для серча выгружает

**Comment by aledyad** [comment]
#13 fixed
